### ISSUE TITLE
I finded a Bug

### ISSUE THREAD

**Issue by SionFu** [TaylanTatli/Moon#12]
Hello, when I was in the use of moon theme, press back button, sometimes meet view will disappear, this is a Bug, in Safari browser will appear such problems,Thanks

**Comment by TaylanTatli** [comment]
I'm sorry but i didn't understand what you mean. Can you show me a screenshot or video of site when bug appears?

**Comment by SionFu** [comment]
when I touch back button, Some times  i meet this BUG

**Comment by TaylanTatli** [comment]
So, you say when you click back button that below the title, content disappears? I don't know how can i test it, because i can't install safari in my linux box.

**Comment by SionFu** [comment]
Yes,   so you see this .

**Comment by libeclipse** [comment]
How about posting a screenshot mate...

**Comment by SionFu** [comment]
just like [EverNote](https://www.yinxiang.com/i/nvIjJH5LaeI?utm_source=service_email&utm_medium=messaging_invitation&utm_campaign=noteShared&messageClaimFlow.emailTrackingCode=noteShared&messageAttachmentValue=1&email_name=messageInvitation-noteShared&email_guid=4cc0a01b-3aed-4b38-87b8-070d47cfce81&email_link=https%3A%2F%2Fwww.yinxiang.com%2Fi%2FnvIjJH5LaeI)

**Comment by TaylanTatli** [comment]
I tested with safari and everything seems ok. I can't help you since you don't give enough info about this. And didn't understand what are you trying to do with that link.

**Comment by SionFu** [comment]
oh this link just show a screenshot with EverNote about this BUG,I have sent to you by email before.

**Comment by TaylanTatli** [comment]
It shows a login page.

**Comment by SionFu** [comment]
Er maybe is likely to register an account

**Comment by TaylanTatli** [comment]
I can't read Chinese. Also i already have an Evernote account and i won't register a site to just look for a screenshot. Please, if you want this to be fixed, be helpful. Because it seems you are making fun of me.
