### ISSUE TITLE
Not Properly Rendering on GHPages

### ISSUE THREAD

**Issue by dSmithShmog** [TaylanTatli/Moon#128]
Hey, I love your theme. There's just one issue. I forked it, edited the config, about, and posts to get a barebones site running for myself. It builds fine locally, but on git it renders without any of the styling. It doesn't throw a build error it just looks like a plain HTML site with the background and logo images. 

Currently my repo's name is myMoon. I'm aware its supposed to be username.github.io I've just been trouble shooting and kept the original files in a separate repo. I'd appreciate it if you've ran into this or knew some fix. I suspect its an issue in my config file but I'm pretty new to all of this. 

Thank you for your time and your theme.

**Comment by matiRLC** [comment]
Hey, I'm facing the same issue. How did you come about it?
