### ISSUE TITLE
How do I create a new page?

### ISSUE THREAD

**Issue by DazzleNova** [TaylanTatli/Moon#135]
I don't know how to add a new page. It will only show an error page.
I create a new folder and add an index.md file in it.  I add it to the navigation and it will only show an error page. Am I even doing it right? I'm kinda new to coding and stuff lol.

**Comment by alejandroandreu** [comment]
You don't need to create any new folder, just navigate to the `_posts` folder. There you will see a bunch of Markdown files (with `.md` extension). 

The files need to be named following the convention `YEAR-MONTH-DAY-title.md` and their contents must be written in [Markdown](https://daringfireball.net/projects/markdown/syntax).

Afterwards, `build` and `serve` the site locally to test your changes.

For more information, please refer to the Jekyll documentation on the topic: https://jekyllrb.com/docs/posts/

**Comment by DazzleNova** [comment]
It works! Thank you so much :)
