### ISSUE TITLE
Add social link to keybase.

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Moon#2]
In the social links section, keybase should be added.

https://keybase.io/

**Comment by libeclipse** [comment]
Example keybase profile: (mine) https://keybase.io/eclipse

**Comment by TaylanTatli** [comment]
I would like to but font awesome doesn't support keybase for now. https://github.com/FortAwesome/Font-Awesome/issues/4095

**Comment by libeclipse** [comment]
Ah. Guess I'll stick stick to putting it in the About Me page then.

**Comment by TaylanTatli** [comment]
I'm sorry. When they support it, i will add.

**Comment by libeclipse** [comment]
Kaybase themselves use fa-key from font awesome. I think it's a better fit than "the strange animal with sunglasses" people know nothing about.

https://fortawesome.github.io/Font-Awesome/icon/key/

**Comment by TaylanTatli** [comment]
I have an exam today. I will add it after that.

**Comment by TaylanTatli** [comment]
Done. I will sleep now. :)

**Comment by libeclipse** [comment]
Thanks.
