### ISSUE TITLE
Build Warning: Layout 'inner' requested in _posts/2016-05-12-example.md does not exist.

### ISSUE THREAD

**Issue by CraigglesO** [TaylanTatli/Moon#21]
I realize I can just remove it. But what would I be missing out on? I am still new to Jekyll, sorry. Your Moon project is INCREDIBLE. Thank you for posting it. :) 👍

**Comment by TaylanTatli** [comment]
Thank you. :) There is no `2016-05-12-example.md` file in `_posts` folder. I assume you added it to test or find somewhere, i don't know. If it's like this `layout: inner` just change `inner` with `post`. Available layouts are in `_layouts` folder.

**Comment by CraigglesO** [comment]
Sorry. :) I found your legitimate links and I threw something fun together!
http://craiggleso.github.io//

It's a little changed up, but the overall theme is the same. Not finnished.. nor I havn't had the heart to change the background yet because it makes me feel like I am in a coffee shop and that makes me really happy.


Thanks a ton for making this! It is fun to play with.
