### ISSUE TITLE
Text is stretched out on mobile.

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Moon#22]
On mobile, the titles of posts are stretched out across the screen, leaving out of place gaps.

![screenshot_2016-05-14-09-10-26](https://cloud.githubusercontent.com/assets/8942495/15267238/0625ce6e-19b4-11e6-82d6-a62ee2e774db.png)

![screenshot_2016-05-14-09-10-10](https://cloud.githubusercontent.com/assets/8942495/15267240/13a103a6-19b4-11e6-903d-311fd40daac7.png)

**Comment by TaylanTatli** [comment]
It's not just for mobile. Problem is text alignment. I set text alignment as justify for all content area. I suppose i should edit it.
