### ISSUE TITLE
Markdown code block render issue

### ISSUE THREAD

**Issue by pratz** [TaylanTatli/Moon#23]
My markdown code block looks like

```
- Some sample code

        print("Hello")
        print("World")
```

I am using markdown space indentation for code block.
When the page is rendered there is one extra space on the first line inside code block.
This can be reproduced easily by using markdown spaces for code block.

**Comment by TaylanTatli** [comment]
Can you try removing this line will fix it?
https://github.com/pratz/pratz.github.io/blob/master/_sass/typography.scss#L123

**Comment by pratz** [comment]
I had already tried it, but its not a perfect fix.
It removes padding for inline code block (``) as well and also lines under code block are not aligned accurately.

I feel its not a css issue rather a rendering issue. If we use chrome inspector we see that first line in the code block has a space in it regardless of the css applied to it.

**Comment by TaylanTatli** [comment]
Can you try other methods for code block like backticks ``` or {% highlight %}{% endhighlight %}.
If they gave same result we can try to fix it, but if not, it must be rendering issue like you said.

**Comment by pratz** [comment]
Three backticks - works fine
{% highlight %}{% endhighlight %} - I am not sure if this is a markdown syntax

All my docs use indentation for code block and changing them to backticks would be time consuming.
Thanks anyways

**Comment by TaylanTatli** [comment]
It's a liquid tag: https://jekyllrb.com/docs/templates/#code-snippet-highlighting

Sorry I couldn't help.

**Comment by libeclipse** [comment]
Three backticks is proper markdown syntax.
