### ISSUE TITLE
Featured image only working with online figs

### ISSUE THREAD

**Issue by gburin** [TaylanTatli/Moon#27]
When I try to add as a featured image to a post an image that is in /assets/img/, only a grey square appears with the title, but when I use a link to any random image online, it works perfectly. 

I am using
feature: /assets/img/image.png 
in the post.

Thanks for the help!

--EDIT--

Just found I needed to add .. before the path (../assets/img/image.png). My bad! Feel free to delete the issue, and I apologize for the error.

**Comment by TaylanTatli** [comment]
It's because you didn't set your `url` in `_config.yml`. When you set your ` url` you don't need `..`, just `assets/img/image.png ` or wherever it is.

**Comment by gburin** [comment]
Perfect, thanks for the quick reply!

**Comment by TaylanTatli** [comment]
You welcome. :smile:
