### ISSUE TITLE
Round reading time.

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Moon#29]
Currently, if a passage contains, for example, ~750 words, so a reading time of just under 4 minutes, it will be rounded down to 3 minutes. It should be rounded to the closest minute, not floored.

**Comment by TaylanTatli** [comment]
It's a liquid problem. See how it works here: https://help.shopify.com/themes/liquid/filters/math-filters#floor
I don't want to mess with javascript just for this.

**Comment by libeclipse** [comment]
There's also https://help.shopify.com/themes/liquid/filters/math-filters#ceil

**Comment by libeclipse** [comment]
I'm not actually that familiar with the layout of the theme and how it all interacts, so no, I haven't tested it myself. But, it looks like it's just a standard ceiling function. If you want me to test it I can do, you'll just have to point me in the right direction. :P

**Comment by libeclipse** [comment]
Is there support for conditions? If so, floor could be used when the value is less than half way above the mark, and ceiling could be used when it's more. This would be more accurate than simply flooring or ceiling the value all the time.

**Comment by TaylanTatli** [comment]
in `_includes/read-time.html`, 
changing 
`assign readtime = content | strip_html | number_of_words | divided_by:site.words_per_minute` 
to 
`assign readtime = content | strip_html | number_of_words | divided_by:site.words_per_minute | ceil` 
should work. I don't know right now.
I have an exam tomorrow, so I can't work on it today.

**Comment by libeclipse** [comment]
That probably will not work, since divided_by apparently floors the value already. I'll test later.

**Comment by TaylanTatli** [comment]
Ok, thank you. Let me know.

**Comment by TaylanTatli** [comment]
@libeclipse this should fix this problem. It's working locally.

**Comment by TaylanTatli** [comment]
for the reference: https://shopify.github.io/liquid/filters/divided_by/#controlling-rounding

**Comment by libeclipse** [comment]
What's the expected behaviour now?

**Comment by TaylanTatli** [comment]
With your example:  750 words / 200 word per minute = 3.75 minute and with rounding it's 4 minute. It was 3 minute before. This is what you want, isn't it? Am I misunderstood?

**Comment by libeclipse** [comment]
So it rounds to the nearest minute now instead of flooring? If so, yeah
that's solved it.
On 16 Jun 2016 14:41, "Taylan Tatlı" <notifications@github.com> wrote:

With your example: 750 words / 200 word per minute = 3.75 minute and with
rounding it's 4 minute. It was 3 minute before. This is what you want,
isn't it? Am I misunderstood?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TaylanTatli/Moon/issues/29#issuecomment-226488009>, or mute
the thread
<https://github.com/notifications/unsubscribe/AIhzn0CeK7yXV8vGarFp2MiCuRknsBgTks5qMVJtgaJpZM4IvcEo>
.

**Comment by TaylanTatli** [comment]
Yep. It rounds to the nearest minute now.

**Comment by libeclipse** [comment]
Sorted fam.
