### ISSUE TITLE
Fira Sans has trouble displaying on some desktops

### ISSUE THREAD

**Issue by rheupler** [TaylanTatli/Moon#31]
It seems like Fira Sans isnt displaying on some screens. Specifically I saw this issue on Windows 10 Chrome and it seems like other people online have the same experience.

**Comment by TaylanTatli** [comment]
I didn't test on Windows 10 but for others, it was working. Can you show me a screenshot? You think it's because of Fira Sans or something else? Did you test with other fonts?

**Comment by TaylanTatli** [comment]
https://github.com/google/fonts/issues/10

It seems I should use Mozilla CDN.

**Comment by TaylanTatli** [comment]
Is it ok now?

**Comment by rheupler** [comment]
I won't be able to test until later today, I'll get back to you to confirm the fix. Thanks!

**Comment by rheupler** [comment]
Works now with the new cdn
