### ISSUE TITLE
why I can't see my new posts after I post it to _posts?

### ISSUE THREAD

**Issue by nuclearDev** [TaylanTatli/Moon#39]
I've post a post to _posts file, and I can find it in github repo, but can't found it in my site.

**Comment by libeclipse** [comment]
Apparently you can see all of them. Not sure what you're on about.

**Comment by TaylanTatli** [comment]
As @libeclipse said, all of them is there. Is this solved?

**Comment by nuclearDev** [comment]
it is solved,thanks！
