### ISSUE TITLE
Question: Add new entries under Projects

### ISSUE THREAD

**Issue by jxchen01** [TaylanTatli/Moon#40]
First of all, thank you for this nice theme!

I have two questions of "projects".

(1) How to add a new entry in the page of "Projects"? For example, I have three projects saved as P1.md, P2.md P3.md (should I use .md files or .html files here?). What is the syntax to add them to the page of "All Projects" (i.e. /projects/index.md)?

(2) If I simply want to change "Projects" to "Work". In your guide, I can find how to change the name in the navigation. How can I change the name in the tabs, the bottom part of the front page?

Many thanks
Jianxu

**Comment by TaylanTatli** [comment]
Thanks. :)

For your first question: You should use `.md` extension and file name should be like that; `year-month-day-title.md`
While writing your post, it must start with Yaml front matter. Example:
```
---
layout: post
title:  "Post Title"
date:   2016-06-27
excerpt: "This is post excerpt. You can delete this line if you want an auto generated excerpt."
project: true
tag:
- tag1
- tag2
- tag3
comments: true
---
```
If it won't be a project post you can remove also `project: true` line. Add this line only for projects.

For your second question:
If you want to change `Projects` to `Works`:
Edit these lines/files and replace `projects` to `works` but pay attention to capitalization;

Edit this file: https://github.com/TaylanTatli/Moon/blob/master/_data/navigation.yml
Edit this file but only `title` and `excerpt`: https://github.com/TaylanTatli/Moon/blob/master/projects/index.md
Edit this lines: https://github.com/TaylanTatli/Moon/blob/master/_layouts/home.html#L41-42
And edit this line: https://github.com/TaylanTatli/Moon/blob/master/_layouts/post.html#L28

Now when you add `projects: true` line to your front matter, they will appear in Works.

I hope, didn't miss anything. And sorry if my explanation is not clear. English is not my native language.

**Comment by jxchen01** [comment]
Thanks a lot. Everything works well now.
