### ISSUE TITLE
can't find any post in post lists after edit post file

### ISSUE THREAD

**Issue by justin94lee** [TaylanTatli/Moon#44]
I can't find my post after modify the post file in _posts/ folder, but I can find the post in tags list page,it's weird

**Comment by TaylanTatli** [comment]
Can you test your repo locally to see if there is any error? I don't have a pc anymore, so i can't check it.

**Comment by xuansamdinh** [comment]
@justin94lee You should give more detail, or close this issue if it have been solved.

Opt-topic: @TaylanTatli Where is your computer now? Why did it gone?

**Comment by TaylanTatli** [comment]
@xuansamdinh It's broken and I don't have money for a new one. (I'm just a poor university student. 😄)
