### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by zhouyuexie** [TaylanTatli/Moon#48]
Browser prompt `Uncaught TypeError: Cannot read property 'appendChild' of null`
I think the following code is not executed

`
{% if page.comments and site.disqus_shortname %}
\<section id="disqus_thread" class="animated fadeInUp"><\/section>
\
{% endif %}
`

this code in `/moon/_layouts/post.html`,i don't know`page.comments` where?
`disqus_shortname` I already filled this out.

**Comment by TaylanTatli** [comment]
http://taylantatli.me/Moon/moon-theme/#comments
To show disqus comments for your post, add `comments: true` to your post’s front matter.

**Comment by zhouyuexie** [comment]
@TaylanTatli thanks you reply.
I try to solve the problem in your way, but I still don't know where the problem is.

In the end, I removed the judgment and joined the Disqus

before:
```html
{% if comments and site.disqus_shortname %}
<section id="disqus_thread" class="animated fadeInUp"></section>
<!-- /#disqus_thread -->
{% endif %}
```

now:
```html
<section id="disqus_thread" class="animated fadeInUp"></section>
```

**Comment by TaylanTatli** [comment]
Sorry,  I don't have a laptop anymore. I can't check the problem. :/

**Comment by xuansamdinh** [comment]
@zhouyuexie Have you modified the code, please make sure the code is:

```
{% if page.comments and site.disqus_shortname %}
```
but not (missed the `page`):
```
{% if comments and site.disqus_shortname %}
```

Check post's front matter.
