### ISSUE TITLE
red page

### ISSUE THREAD

**Issue by godofhand** [TaylanTatli/Moon#49]
There is red page while loading or refreshing.

**Comment by TaylanTatli** [comment]
It's background color to show while background image is loading. You want to change it? I don't understand the problem.

**Comment by godofhand** [comment]
Yes, can I change to other color like white or black because it seems more match the theme. Or even add some loading page.

**Comment by chrstntdd** [comment]
@godofhand You can alter the background color by navigating to ```variables.scss``` within the ```_sass``` directory and altering the ```$bodycolor``` variable to whatever color you desire.

**Comment by libeclipse** [comment]
Somewhat related is that on mobile when scrolling, the background jitters and the red is exposed creating a really ugly effect.

**Comment by godofhand** [comment]
@chrstntdd  Thanks for help, problem solved. Is there a way to prevent to show the $bodycolor? or replace it with some progress bar.

**Comment by libeclipse** [comment]
It lasts for a split second why would you want a progress bar?

**Comment by TaylanTatli** [comment]
@libeclipse I see same thing on mobile,  for my case it's because address bar hiding while scrolling. I looked for a solution but couldn't find a clean one. 

@godofhand Jekyll sites are too fast for a loading animation.
