### ISSUE TITLE
Enabling google analytics

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Moon#53]
In `_includes/scripts` I see `{% if site.google.analytics %}`but I don't see that in config.yml. Basically what I'm asking is, how do you enable google analytics?

**Comment by TaylanTatli** [comment]
https://github.com/libeclipse/libeclipse.github.io/blob/master/_config.yml#L35

**Comment by TaylanTatli** [comment]
Also uncomment line 33 `google:` too.

**Comment by libeclipse** [comment]
Pushed a commit. Is that correct?

**Comment by TaylanTatli** [comment]
Yep. It's correct.

**Comment by libeclipse** [comment]
Thanks
