### ISSUE TITLE
CSS dont load.

### ISSUE THREAD

**Issue by alipseight** [TaylanTatli/Moon#60]
I forked your repo, i was edited the _confing.yml but when i acess alipseight.github.io, show this:

http://prntscr.com/ce7mwq

**Comment by dutzu-ro** [comment]
Check out your error messages. Mine were file not found because in _config.yml, the url was setup to my current domain. It has solved when changed the url parameter to: https://username.github.io

**Comment by alipseight** [comment]
Done.
 
 The Firefox has conflict with the _http_ so I changed to _http_**s** in files that show me on the console log.
