### ISSUE TITLE
Question / Feature Request - Medium social button

### ISSUE THREAD

**Issue by ToddMurphy92** [TaylanTatli/Moon#69]
I understand this seems kind of redundant given that most people using Jekyll would also be using it as their only/main blogging platform but I was wondering would it be possible to add medium to the list of social platforms this theme can integrate using config.yml?

**Comment by nikhiljolly** [comment]
Hey @ToddMurphy92 ,
Sure, why not? You can add it yourself if you want. I think the font-awesome api that the dev is using for the icons already has a medium icon. It goes by the class "fa fa-fw fa-medium" I think.

Like you modified for the github icon issue, modify this:
https://github.com/TaylanTatli/Moon/blob/master/_config.yml
And this (using the class I am referring to)
https://github.com/TaylanTatli/Moon/blob/master/_includes/social-links.html
And wherever you want to use your medium icon/link.

You should understand what I am saying when you have a closer look at the social-links.html

**Comment by ToddMurphy92** [comment]
Wow it worked! Thanks nikhiljolly :)

Now I'm adding it to my about bar, assuming that works I'll then close this off.

**Comment by ToddMurphy92** [comment]
Both working now, thanks again. I'll close this off now.
