### ISSUE TITLE
"We were unable to load Disqus."

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Moon#7]
At the bottom of any pages where I enable comments, that message shows up.

Ideas?

**Comment by libeclipse** [comment]
Never mind I'm just stupid. :P

**Comment by AurevoirXavier** [comment]
I have the same question.
How do you fix it? :-)

**Comment by libeclipse** [comment]
It's in the config file.

**Comment by AurevoirXavier** [comment]
You mean the ```disqus_shortname:``` ?
But I already set it.

**Comment by AurevoirXavier** [comment]
Oh, I know. I should set `xxx.github.io` in Disqus rather than my domain name.
