### ISSUE TITLE
Jekyll-Hook is no longer mantained

### ISSUE THREAD

**Issue by jtemporal** [TaylanTatli/Moon#73]
Hi, awesome template :heart:!
I forked it and was trying to use it but I just found out (after installing the gems that were missing :smile:) that [jekyll-hook gem](https://github.com/developmentseed/jekyll-hook) is no longer maintained.

So I had two ideas:
 1 - clone jekyll-hook repo and build it on my notebook;
or
 2 - change the template to no longer need this gem;

keeping in mind the opportunity to learn a little bit more about Jekyll templates and all, I'm new to ruby and Jekyll, and also that is Hacktoberfest time (yeey open source \o/), I would like to go with option 2 and make an PR.

Would like to discuss the better way to this.

Thanks :slightly_smiling_face:

**Comment by TaylanTatli** [comment]
Sorry I was late. I don't understand what you mean. I didn't use jekyll-hook gem. So does it really relevant to this theme if it's not maintained anymore.

**Comment by jtemporal** [comment]
I don't know how or what I did that the problema I was having no longer exists... So i'm closing this issue... But thanaks anyways =)
