### ISSUE TITLE
How to use the projects page and folder?

### ISSUE THREAD

**Issue by MichaelMMeskhi** [TaylanTatli/Moon#79]

**Comment by tanto259** [comment]
In your `.md` or `.html` file in _posts folder, ensure that there are `project: true` in the header.

Example:
```
---
layout: post
title:  "Moon Jekyll Theme"
date:   2016-04-06
excerpt: "Minimal, one column Jekyll theme for your blog."
project: true
tag:
- jekyll 
- moon
- blog
- about
- theme
comments: true
---
```
See: [https://raw.githubusercontent.com/TaylanTatli/Moon/master/_posts/2016-03-21-moon-theme.md](https://raw.githubusercontent.com/TaylanTatli/Moon/master/_posts/2016-03-21-moon-theme.md)
