### ISSUE TITLE
Make back button in project post go to projects page

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Moon#8]
Currently, if you're viewing a project post, and you click tha back button at the top of the page, it takes you to the list of all posts, not including projects.

It'd be much better if that button took you to the projects page. Only when viewing a normal post should it take you to the list all posts page.

**Comment by TaylanTatli** [comment]
Ah, thank you. I thought i already did that. But it seems i did it for page layout instead of project layout by mistake.

**Comment by TaylanTatli** [comment]
Fixed. Thanks.
