### ISSUE TITLE
Change Markdown font

### ISSUE THREAD

**Issue by MichaelMMeskhi** [TaylanTatli/Moon#80]

**Comment by BedirT** [comment]
There is a problem with coding part, I guess that is the problem. Normal Text is OK, but for coding part the font is disturbing ... You can [Check here](http://bedirtapkan.me/Prime-Number-Factorization/ ) if you want

**Comment by tanto259** [comment]
The normal text is Fira Sans, while the code text is Inconsolata. To change it, just add the font to the `assets/fonts` folder then edit `_sass/vendor/fonts.scss` with the proper font you wanted.

See: [https://github.com/TaylanTatli/Moon/blob/master/_sass/vendor/fonts.scss](https://github.com/TaylanTatli/Moon/blob/master/_sass/vendor/fonts.scss)

**Comment by BedirT** [comment]
Thanks , It worked 👍
