### ISSUE TITLE
ABSOLUTE PATH ISSUE!

### ISSUE THREAD

**Issue by KevinSirius** [TaylanTatli/Moon#85]
I cloned this theme into my repository and all the js and css are not correctly displayed. After struggling using inspect elements, I found that the issue is caused my relative path {{ site.url }} is not correctly replaced by the url you writes in config.yml

In order to fix this issue, you need to replace {{ site.url }} with your own https://XXX.github.io (please add http or https depends on which one you are using.)

P.S. After I replaced the one in JS and css part (start with notation JS and css), I found that the menu on the left does not work. In order to fix this issue, I replaced all the site.url with my own domain. But after this editing, you should be aware that your repository of your github page is NO LONGER DUPLICATABLE, which means they have to go thru the same pattern I listed above after FORKING OR CLONING THIS REPO but not yours. Dun Braggin and say check out my repo. :)

This should work fine and if you have more issue go talk to TaylanTatli.

**Comment by KevinSirius** [comment]
oh I think you should add quotation marks in config.yml when you write down your url.
:)

**Comment by rohithasrk** [comment]
@KevinSirius , you mean replacing every instance of site.url with absolute path?

**Comment by KevinSirius** [comment]
@rohithasrk Sorry I did not see the issue #77 before. I said put the whole url inside the config file in my last comment and maybe I did not clarify it. Sorry for that.
