### ISSUE TITLE
navbar doesn't collapse when using https

### ISSUE THREAD

**Issue by libeclipse** [TaylanTatli/Moon#9]
When using https, the navbar on the left stays open with everything extended.

**Comment by libeclipse** [comment]
Example: https://libeclipse.me/

**Comment by TaylanTatli** [comment]
Are your sure? When i visit your site, everything is ok.

**Comment by libeclipse** [comment]
Did you change the HTTP to HTTPS?

What browser?

**Comment by TaylanTatli** [comment]
It's chromium. And yes viewing it with https. Which browser do you use?

**Comment by libeclipse** [comment]
I was using Google chrome at college. I'll try reproducing again at home.

**Comment by TaylanTatli** [comment]
Ok. Can you check if javsacript enabled? Because there is a fallback for no-js. If javascript not enabled, nav will not collapse.

**Comment by libeclipse** [comment]
Can you think of a link between that fallback and HTTPS? I'll debug the
connection. Maybe a https was missed somewhere.

**Comment by libeclipse** [comment]
Here's what I'm seeing:

https://i.imgsafe.org/1fb956f.png

**Comment by TaylanTatli** [comment]
I don't think https will affect. Modernizr just check if your browser support javascript or not. Can you show me a screenshot of site with inspector screen (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>). I wan't to check html tags.

**Comment by libeclipse** [comment]
Developer tools have been blocked it seems. I'll try and reproduce the error at home. It may turn out that it's just a local problem with this network.

**Comment by TaylanTatli** [comment]
It also can be something about CloudFlare Rocket Loader. Never used it but it seems, it does something about js files. There is an error on your site:
```
GET https://libeclipse.me/cdn-cgi/pe/bag2?r[]=https%3A%2F%2Flibeclipse.me%2Fass…y.fitvid.min.js&r[]=https%3A%2F%2Flibeclipse.me%2Fassets%2Fjs%2Fscripts.js 405 ()
```

**Comment by libeclipse** [comment]
Disabled SSL altogether. It was causing too many problems until the point where the site even refused to load.
