### ISSUE TITLE
Stop redirecting to custom domain

### ISSUE THREAD

**Issue by pegasusearl** [TaylanTatli/Moon#90]
So I have set a custom domain, and then it always opened my custom domain everytime I opened my name.github.io.
People said I should deleted CNAME file, and I deleted it but it's still redirecting to my custom domain. And everytime I added another new custom domain, it always redirected to old one. Even if I deleted the repo and forked it again, nothing change. How to stop that?
Thank you

PS: I don't know how to add "question" label. Im sorry, first time using github.

**Comment by libeclipse** [comment]
This isn't a question related to this project. If all else fails you could contact github support. Please close this issue.

**Comment by pegasusearl** [comment]
ok, thanks for the info
