### ISSUE TITLE
The setup info link isn't working

### ISSUE THREAD

**Issue by abhi18av** [TaylanTatli/Moon#92]
Hi @TaylanTatli 

I loved this theme, wished to use it for an environment oriented NGO but I've run into the dead-link towards the end of the `README.md` which is supposed to outline the setup feature.

1. So, being a newbie I just tried opening the `index.html` using the python server command - doesn't seem to work.

2. Also, I've noticed the landing page loads a bit slow 

3. How can I convert this blog to give credit to multiple authors?

Would you please guide me a bit? 

Happy new year 😄

**Comment by TaylanTatli** [comment]
Sorry, I forgot to update link. Here: `http://taylantatli.github.io/Moon/moon-theme/`

**Comment by abhi18av** [comment]
Oh, got it :+1:
